[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = [
  "oraclenets"
]

[programs.localnet]
oraclenets = "7QJjHQAsytvvrNmqPJajKYKXwZXtVHd8T3t9bBVvxtMY"

[programs.devnet]
oraclenets = "7QJjHQAsytvvrNmqPJajKYKXwZXtVHd8T3t9bBVvxtMY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
